# Generated by Django 3.2.4 on 2022-03-06 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.ForeignKey(db_column='conversationId', on_delete=django.db.models.deletion.CASCADE, related_name='conversationMembers', to='messenger_backend.conversation')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='messenger_backend.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
