# Generated by Django 3.2.4 on 2022-02-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipientId', models.IntegerField()),
                ('hasBeenRead', models.BooleanField()),
                ('conversation', models.ForeignKey(db_column='conversationId', on_delete=django.db.models.deletion.CASCADE, related_name='messagesRead', to='messenger_backend.conversation')),
                ('message', models.ForeignKey(db_column='messageId', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='messenger_backend.message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
